name: Build lint

on:
  push:
    branches: "*"
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"

      # Frontend steps
      - name: Install frontend dependencies
        run: npm ci
        working-directory: ./front

      - name: Build frontend
        run: npm run build --if-present
        working-directory: ./front

      - name: Type-check frontend
        run: npm run type-check
        working-directory: ./front

      - name: Lint frontend
        run: npm run lint
        working-directory: ./front

      # API steps
      - name: Install API dependencies
        run: npm ci
        working-directory: ./api

      - name: Build API
        run: npm run build --if-present
        working-directory: ./api

      - name: Type-check API
        run: npm run type-check
        working-directory: ./api

      - name: Lint API
        run: npm run lint
        working-directory: ./api
